"""enforce one account per user

Revision ID: 3eb2ab5a2d3b
Revises: c04bc9c0f5d6
Create Date: 2026-09-10 00:52:19.175836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb2ab5a2d3b'
down_revision: Union[str, Sequence[str], None] = 'c04bc9c0f5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('nickname', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
