"""add account id and enforce one account per user

Revision ID: c04bc9c0f5d6
Revises: 4189f637b841
Create Date: 2026-09-08 14:28:42.633011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c04bc9c0f5d6'
down_revision: Union[str, Sequence[str], None] = '4189f637b841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('status', sa.VARCHAR(length=10), nullable=False))
    op.add_column('accounts', sa.Column('nickname', sa.VARCHAR(length=50), nullable=False))
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_column('accounts', 'nickname')
    op.drop_column('accounts', 'status')
    # ### end Alembic commands ###
