"""transaction table account name changed

Revision ID: cac1558b0f80
Revises: 337553d2daea
Create Date: 2026-09-14 14:37:30.656632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac1558b0f80'
down_revision: Union[str, Sequence[str], None] = '337553d2daea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('sender_account_id', sa.Uuid(), nullable=True))
    op.add_column('transactions', sa.Column('receiver_account_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('transactions_sender_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('transactions_receiver_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'accounts', ['receiver_account_id'], ['account_id'])
    op.create_foreign_key(None, 'transactions', 'accounts', ['sender_account_id'], ['account_id'])
    op.drop_column('transactions', 'receiver_id')
    op.drop_column('transactions', 'sender_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('receiver_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_receiver_id_fkey'), 'transactions', 'accounts', ['receiver_id'], ['account_id'])
    op.create_foreign_key(op.f('transactions_sender_id_fkey'), 'transactions', 'accounts', ['sender_id'], ['account_id'])
    op.drop_column('transactions', 'receiver_account_id')
    op.drop_column('transactions', 'sender_account_id')
    # ### end Alembic commands ###
